### ISSUE TITLE
Automatic-Module-Name attributes, please?

### ISSUE THREAD

**Issue by lenborje** [christian-schlichtherle/truevfs#7]
Could you please add a `Automatic-Module-Name` attribute to all your jar artifacts?

I'm slowly migrating to Java 11 and modularising my applications. Since I use TrueVFS, I have tried to use them on the module path as Automatic Modules. The JVM will then assign an "automatic module name" to them based on the JAR file name, e.g. `foo-bar-1.2.jar` would be assigned the module name `foo.bar`.
For TrueVFS this fails, however, for two different reasons:

1. Some of your artefacts have names with the word "default" in them, e.g. `truecommons-key-default-2.5.0.jar`. This will cause the JVM Automatic Module Name heuristics to fail, as the heuristically assigned name, e.g. `truecommons.key.default`, would then contain the reserved identifier `default`, which is forbidden.
2. Some versions of your artefacts have version numbers embedded in their names, e.g `truevfs-profile-base_2.12-0.12.0.jar`, which causes similar problems. The implied name would be `truevfs.profile.base.2.12`, which since it contains pure numbers (`2` and `12`) is not allowed.

The simplest solution for both problems would be to add a `Automatic-Module-Name` attribute to the `MANIFEST.MF` of all jars. This would be ignored unless the jars are used on the Module Path.

I would be very happy if you could this. I'm currently forced to rename or repack all these troublesome JARs and it is most impractical.

Additional info with further links:
[https://stackoverflow.com/questions/46741907/what-is-an-automatic-module](https://stackoverflow.com/questions/46741907/what-is-an-automatic-module)
[http://branchandbound.net/blog/java/2017/12/automatic-module-name/](http://branchandbound.net/blog/java/2017/12/automatic-module-name/)

**Comment by christian-schlichtherle** [comment]
It's done in the latest version, TrueVFS 0.12.2.
